version: '3'
services:
  api:
    image: planitnerd/planitnerd-api
    build: .
    networks:
      - backend
    ports:
      - '4444:4444'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - '27017:27017'

  web-cli:
    image: planitnerd/planitnerd-api
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
